/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.stocks.StockDAO;
import model.stocks.StockDTO;
import uyen.ulti.MyValidation;

/**
 *
 * @author HP
 */
public class StocksJFrame extends javax.swing.JFrame {

    DefaultTableModel tblModelStock = null;

    /**
     * Creates new form StocksJFrame
     *
     * @throws java.lang.Exception
     */
    public StocksJFrame() throws Exception {
        initComponents();
        tblModelStock = (DefaultTableModel) tblViewStock.getModel();
        StockDAO dao = new StockDAO();
        List<StockDTO> list = dao.generateData();
        showTable(list);
    }

    private void showTable(List<StockDTO> list) {
        tblModelStock.setRowCount(0);
        for (StockDTO dto : list) {
            tblModelStock.addRow(dto.toVector());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewStock = new javax.swing.JTable();
        btnInsert = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ParentDialog");
        setResizable(false);

        tblViewStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "StockID", "StockName", "Address", "DateAvailable", "Note"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblViewStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViewStockMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblViewStock);
        if (tblViewStock.getColumnModel().getColumnCount() > 0) {
            tblViewStock.getColumnModel().getColumn(0).setResizable(false);
            tblViewStock.getColumnModel().getColumn(0).setPreferredWidth(1);
            tblViewStock.getColumnModel().getColumn(1).setResizable(false);
            tblViewStock.getColumnModel().getColumn(1).setPreferredWidth(5);
            tblViewStock.getColumnModel().getColumn(2).setResizable(false);
            tblViewStock.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblViewStock.getColumnModel().getColumn(3).setResizable(false);
            tblViewStock.getColumnModel().getColumn(3).setPreferredWidth(5);
            tblViewStock.getColumnModel().getColumn(4).setResizable(false);
        }

        btnInsert.setText("Insert to DB");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(btnInsert)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInsert)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        int row = tblViewStock.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please choose a row");
            return;
        }

//        String idString = (String) tblModelStock.getValueAt(row, 0);
        int id = (Integer) tblModelStock.getValueAt(row, 0);
        String name = (String) tblModelStock.getValueAt(row, 1);
        String address = (String) tblModelStock.getValueAt(row, 2);
//        String dateString = (String) tblModelStock.getValueAt(row, 3);
        Date date = (Date) tblModelStock.getValueAt(row, 3);
        String note = (String) tblModelStock.getValueAt(row, 4);

//        int id = 0;
//        Date date = null;
        String valid = "";
//        if (idString.isEmpty()) {
//            valid += "ID can't be empty\n";
//        } else {
//            try {
//                id = Integer.parseInt(idString);
//            } catch (NumberFormatException e) {
//                valid += "ID must be a number\n";
//            }
//
//        }
//        if (name.isEmpty()) {
//            valid += "Name can't be empty\n";
//        }
//        if (address.isEmpty()) {
//            valid += "Address can't be empty\n";
//        }
//        if (dateString.isEmpty()) {
//            valid += "Date can't be empty\n";
//        } else {
//            if (MyValidation.checkDate(dateString)) {
//                date = Date.valueOf(dateString);
//            } else {
//                valid += "Invalid date format (yyyy-MM-dd)\n";
//            }
//        }
//        if (note.isEmpty()) {
//            note = " ";
//        }
//
        if (valid.isEmpty()) {
            try {
                StockDAO dao = new StockDAO();
                if (dao.insertToDatabase(id, name, address, date, note)) {
                    JOptionPane.showMessageDialog(this, "Insert successfully!");
                } else {
                    JOptionPane.showMessageDialog(this, "Insert failed!");
                }
            } catch (Exception ex) {
                Logger.getLogger(StocksJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, valid);
        }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void tblViewStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViewStockMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tblViewStockMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StocksJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StocksJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StocksJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StocksJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new StocksJFrame().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(StocksJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsert;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblViewStock;
    // End of variables declaration//GEN-END:variables
}
